theory Constraints_Demo
  imports Main
begin

text \<open>
  Demonstrate the purpose of the @{attribute constraints} tag on elimination
  (case-analysis) rules generated by @{command inductive}.
\<close>

section \<open>Setup: a simple inductive predicate\<close>

inductive myrel :: "nat \<Rightarrow> nat \<Rightarrow> bool" where
  base: "myrel 0 0"
| step: "myrel n m \<Longrightarrow> myrel (Suc n) (Suc m)"

text \<open>The generated elimination rule @{thm myrel.cases} has shape:
  @{thm myrel.cases[no_vars]}

  It has \<open>constraints = 2\<close> because @{const myrel} takes 2 arguments,
  producing 2 equality premises per case (e.g.\ \<open>a = 0\<close> and \<open>b = 0\<close>
  in the base case).
\<close>

section \<open>ML: inspect the constraints tag\<close>

ML \<open>
  val k = Rule_Cases.get_constraints @{thm myrel.cases};
  val _ = writeln ("myrel.cases constraints = " ^ string_of_int k)
\<close>

ML \<open>
  val k2 = Rule_Cases.get_constraints @{thm even.cases};
  val _ = writeln ("even.cases constraints = " ^ string_of_int k2)
\<close>

ML \<open>
  val k3 = Rule_Cases.get_constraints @{thm nat.induct};
  val _ = writeln ("nat.induct constraints = " ^ string_of_int k3)
\<close>

section \<open>ML: show what mark\_constraints does to the rule\<close>

ML \<open>
  val ctxt = \<^context>
  val rule = @{thm myrel.cases}
  val _ = writeln ("ORIGINAL rule:\n" ^
    Syntax.string_of_term ctxt (Thm.prop_of rule))

  (* mark_constraints rewrites the first k equality premises per case
     from  (x = t)  to  (induct_equal x t),  protecting them from simp *)
  val marked = Induct.mark_constraints
        (Rule_Cases.get_constraints rule) ctxt rule
  val _ = writeln ("\nAFTER mark_constraints:\n" ^
    Syntax.string_of_term ctxt (Thm.prop_of marked))

  (* unmark restores them *)
  val unmarked = Induct.unmark_constraints ctxt marked
  val _ = writeln ("\nAFTER unmark_constraints:\n" ^
    Syntax.string_of_term ctxt (Thm.prop_of unmarked))
\<close>

section \<open>Why it matters: proof with \<open>cases\<close>\<close>

text \<open>
  The \<open>cases\<close> method with its built-in simplification step uses
  @{ML Induct.mark_constraints} to protect the equality premises.

  Consider: @{prop \<open>myrel a b \<Longrightarrow> a = b\<close>}.
  After case-splitting on @{const myrel}, the base case gives premises
  \<open>a = 0\<close> and \<open>b = 0\<close>.  If the simplifier were allowed to substitute
  these equalities, they would vanish and the case context would lose
  the named bindings.  The @{attribute constraints} tag tells the method
  how many such equality premises to protect.
\<close>

lemma "myrel a b \<Longrightarrow> a = b"
proof (cases rule: myrel.cases)
  \<comment> \<open>The equality premises \<open>a = 0, b = 0\<close> survive because
      they were wrapped in @{const induct_equal} during
      the method's internal simplification pass.\<close>
  case base
  then show ?thesis by simp
next
  case (step n m)
  \<comment> \<open>Here we get \<open>a = Suc n\<close>, \<open>b = Suc m\<close>, \<open>myrel n m\<close>
      --- the equalities are preserved as named premises.\<close>
  then show ?thesis by (induction rule: myrel.induct) simp_all
qed

end
